import { getMonthlyPdSummary } from './pdSummary';
import type { UserProgress } from './progress';

export function buildEvidencePackMarkdown(progress: UserProgress, monthKey: string) {
  const summary = getMonthlyPdSummary(progress, monthKey);

  const lines = [
    `# DCSPrep Evidence Pack — ${summary.monthKey}`,
    '',
    '> This summary is generated from local PD activity. It contains no private student, staff, or incident data.',
    '',
    `- Total PD time: ${summary.totalMinutes} minutes`,
    `- Entries logged: ${summary.entryCount}`,
    `- Topics covered: ${summary.topicsCovered.length ? summary.topicsCovered.join(', ') : 'None yet'}`,
    `- Weak areas touched: ${summary.weakTopicsTouched.length ? summary.weakTopicsTouched.join(', ') : 'None yet'}`,
    `- Suggested next focus: ${summary.suggestedNextFocus}`,
    '',
    '## Entry summary',
    ''
  ];

  if (!summary.entries.length) {
    lines.push('No PD entries logged for this month yet.');
  } else {
    summary.entries.forEach((entry) => {
      lines.push(`### ${entry.date} — ${entry.minutes} min`);
      lines.push('');
      lines.push(`- **Type:** ${entry.type || 'reflection'}`);
      if (entry.resource) lines.push(`- **Resource:** ${entry.resource}`);
      if (entry.topic) lines.push(`- **Topic:** ${entry.topic}`);
      if (entry.moduleIds?.length) lines.push(`- **Modules referenced:** ${entry.moduleIds.join(', ')}`);
      if (entry.scenarioIds?.length) lines.push(`- **Scenarios:** ${entry.scenarioIds.join(', ')}`);
      if (entry.weakTopicsTouched?.length) lines.push(`- **Weak topics touched:** ${entry.weakTopicsTouched.join(', ')}`);
      if (entry.weakTopicsImproved?.length) lines.push(`- **Weak topics improved:** ${entry.weakTopicsImproved.join(', ')}`);
      lines.push('');
      lines.push(`**Evidence summary:** ${entry.learned}`);
      if (entry.reflection) {
        lines.push('');
        lines.push(`**Reflection:** ${entry.reflection}`);
      }
      lines.push('');
    });
  }

  lines.push('', '---', '', 'Generated by DCSPrep local PD tracking.');
  return lines.join('\n');
}
