import { getMonthlyPdSummary } from './pdSummary';
import type { PDLogEntry, UserProgress } from './progress';

function hasAcademicAlignmentEvidence(entries: PDLogEntry[]) {
  return entries.some((entry) => {
    const text = `${entry.resource} ${entry.topic} ${entry.learned}`.toLowerCase();
    return (
      entry.templateId === 'academic-pd' ||
      text.includes('rbc') ||
      text.includes('smitb') ||
      text.includes('academic pd') ||
      entry.moduleIds?.some((moduleId) => moduleId.startsWith('rbc-') || moduleId.startsWith('smitb-'))
    );
  });
}

export function buildEvidencePackMarkdown(progress: UserProgress, monthKey: string) {
  const summary = getMonthlyPdSummary(progress, monthKey);
  const includesAcademicAlignment = hasAcademicAlignmentEvidence(summary.entries);

  const settings = progress.evidencePackSettings ?? {
    includeCertificates: true,
    includeLinks: true,
    privacyReminderAccepted: false
  };

  const lines = [
    `# SupportOps Career Lab Career Evidence Pack — ${summary.monthKey}`,
    '',
    '> This summary is generated from local PD activity. It contains no private student, staff, or incident data.',
    '',
    `- Total PD time: ${summary.totalMinutes} minutes`,
    `- Entries logged: ${summary.entryCount}`,
    `- Topics covered: ${summary.topicsCovered.length ? summary.topicsCovered.join(', ') : 'None yet'}`,
    `- Weak areas touched: ${summary.weakTopicsTouched.length ? summary.weakTopicsTouched.join(', ') : 'None yet'}`,
    `- Suggested next focus: ${summary.suggestedNextFocus}`,
    `- Include optional links: ${settings.includeLinks ? 'Yes' : 'No'}`,
    `- Include certificate references: ${settings.includeCertificates ? 'Yes' : 'No'}`,
    `- Academic alignment evidence: ${includesAcademicAlignment ? 'Informal RBC/SMITB PD alignment included' : 'None logged this month'}`,
    '',
    '## Career evidence overview',
    '',
    'This export highlights your practical growth, strongest and weakest skill areas, and portfolio-safe evidence for managers or interviews.',
    '',
    '## Academic alignment note',
    '',
    includesAcademicAlignment
      ? 'RBC/SMITB references in this export are informal professional-development alignment notes. They do not claim formal university credit, certification, or official assessment completion unless separately evidenced in the external academic system.'
      : 'No RBC/SMITB academic-alignment entries were detected for this export period.',
    '',
    '## Entry summary',
    ''
  ];

  if (!summary.entries.length) {
    lines.push('No PD entries logged for this month yet.');
  } else {
    summary.entries.forEach((entry) => {
      lines.push(`### ${entry.date} — ${entry.minutes} min`);
      lines.push('');
      lines.push(`- **Type:** ${entry.type || 'reflection'}`);
      if (entry.resource) lines.push(`- **Resource:** ${entry.resource}`);
      if (entry.topic) lines.push(`- **Topic:** ${entry.topic}`);
      if (entry.moduleIds?.length) lines.push(`- **Modules referenced:** ${entry.moduleIds.join(', ')}`);
      if (entry.scenarioIds?.length) lines.push(`- **Scenarios:** ${entry.scenarioIds.join(', ')}`);
      if (entry.weakTopicsTouched?.length) lines.push(`- **Weak topics touched:** ${entry.weakTopicsTouched.join(', ')}`);
      if (entry.weakTopicsImproved?.length) lines.push(`- **Weak topics improved:** ${entry.weakTopicsImproved.join(', ')}`);
      lines.push('');
      lines.push(`**Evidence summary:** ${entry.learned}`);
      if (entry.reflection) {
        lines.push('');
        lines.push(`**Reflection:** ${entry.reflection}`);
      }
      if (entry.evidenceLink) {
        lines.push('');
        lines.push(`- **Evidence:** ${settings.includeLinks ? entry.evidenceLink : '(links omitted as requested)'}`);
      }
      lines.push('');
    });
  }

  lines.push('', '---', '', 'Generated by DCSPrep local PD tracking.');
  return lines.join('\n');
}
